# Path to your oh-my-zsh installation.
ZSH_TMUX_AUTOSTART="true"
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(gitfast composer common-aliases git-extras git-hubflow npm sudo wd)

# User configuration

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/usr/local/bin/bin:/usr/local/git/bin:$PATH"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

source ~/.gitpro

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
 #if [[ -n $SSH_CONNECTION ]]; then
 #  export EDITOR='vim'
#fi
# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias .2='cd ../../'
alias .3='cd ../../../'
alias .4='cd ../../../../'
alias .5='cd ../../../../../'
alias .6='cd ../../../../../../'
alias bk='cd $OLDPWD'
alias rm='rm -i'
alias grep='grep --color=auto'
alias mkdir='mkdir -pv'

#process & file related aliases
alias cache='sudo sync && sudo echo 3 > /proc/sys/vm/drop_caches'

#version control
alias ga='git add -A'
alias gc='git commit -m'
alias gp='git push origin $(current_branch)'
alias gpm='git push origin master'
alias gpd='git push origin develop'
alias gl='git log'
alias glg='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit'
alias gtl='git tag -l'
alias gs='git status'
alias gh='git stash'
alias gha='git stash apply'
alias ghp='git stash pop'
alias ghd='git stash drop'
alias ghs='git stash show -p stash@{0}'
alias ungit="find . -name '.git' -exec rm -rf {} \;"

#application specific
alias art='php artisan' #laravel
alias srv='php artisan serve' #laravel
alias tnk='php artisan tinker' #laravel
alias gmig='php artisan generate:migration'
alias gcon='php artisan generate:controller'
alias gmod='php artisan generate:model'
alias cda='composer dump-autoload -o'
alias cc='./vendor/bin/codecept'
alias ccc='./vendor/bin/codecept run --coverage-html'
alias ccu='./vendor/bin/codecept run Unit'
alias cca='./vendor/bin/codecept run Acceptance'
alias ccf='./vendor/bin/codecept run Functional'
alias ccr='./vendor/bin/codecept run'
alias py='python'

#function aliases
alias ghc=ghc
alias mkcd=mkcd
alias grl=grl
alias gac=gac
alias gacm=gacm
alias gacd=gacd
alias ggacm=gulpacm
alias ggac=gulpac
##functions
ghc() {
    git clone git@github.com:$1/$2
}
gac() {
    git add -A && git commit -m "$1"
}
gacm() {
    git add -A && git commit -m "$1" && git push origin master
}
gacd() {
    git add -A && git commit -m "$1" && git push origin develop
}
gulpacm() {
    gulp && git add -A && git commit -m "$1" && git push origin master
}
gulpac() {
    gulp && git add -A && git commit -m "$1"
}

grl() { grep -rl "$1" * }
mkcd() {
    if [ -z $1 ]; then
        echo -e \e[0;31;1mUsage: mkcd [directory]\e[m;
    else
        if [ -d $1 ]; then
            echo Changed to $1.;
            cd $1;
        else
            mkdir $1;
            echo Created $1;
            cd $1;
        fi;
    fi
}
